### ISSUE TITLE
Create Pecha abstraction (4 days)

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#1]
## Description 
This is about creating a Pecha abstraction in a toolkit-v2 and has the ability to write and read annotations as well their metadata. The data should be stored in the data model in [STAM](https://stam-python.readthedocs.io/en/latest/).

## Source Link
[Chojuk alignment](https://github.com/Esukhia/chojuk-alignement)

## Expected Output
A Pecha Abstraction with feature of writing and reading Pecha in stam format.

- [x] Write segment annotation
- [x] Read segment annotation
- [x] Write multiple versions of same layer type
- [x] Write Pecha's metadata, use pydantic

Pecha structure example:

```
pecha_id
- pecha_id.opf
     - meta.json
     - base
          - 1AE3.txt
          - ...
     - layers
          - 1AE3
              - segment-da11.json
              - segment-fsd1.json
              - tsawa-11ws.json
```

Pecha's Metadata attrs
- id: str
- title: list[str]
- author: list[str]
- created_at: datetime
- source: str
- source_metadata: dict

**Comment by ta4tsering** [comment]
done with the write, currently working writing test cases to pass the sanity test.

**Comment by ta4tsering** [comment]
continuing with the current flow and metadata class.

**Comment by kaldan007** [comment]
Going to work on loading Meta data
