### ISSUE TITLE
OPT2016: parse tenbarma translations

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#33]
@tenzin3, please parse the new files added here:

https://github.com/OpenPecha/pecha.org-data/tree/main/input%20texts/tenbarma%20translations

NT needs them as demo for a meeting tomorrow or so.
Thank you

**Comment by tenzin3** [comment]
@ngawangtrinley , @drupchen , @lobsam .

Below are the serialized json.
[tenbarma_children_bo.json](https://github.com/user-attachments/files/16939884/tenbarma_children_bo.json)
[tenbarma_children_en.json](https://github.com/user-attachments/files/16939869/tenbarma_children_en.json)
[tenbarma_children_zh.json](https://github.com/user-attachments/files/16939870/tenbarma_children_zh.json)
[tenbarma_dz.json](https://github.com/user-attachments/files/16939883/tenbarma_dz.json)
[tenbarma_en.json](https://github.com/user-attachments/files/16939875/tenbarma_en.json)
[tenbarma_es.json](https://github.com/user-attachments/files/16939872/tenbarma_es.json)
[tenbarma_fr.json](https://github.com/user-attachments/files/16939865/tenbarma_fr.json)
[tenbarma_hi.json](https://github.com/user-attachments/files/16939876/tenbarma_hi.json)
[tenbarma_ja.json](https://github.com/user-attachments/files/16939877/tenbarma_ja.json)
[tenbarma_ko.json](https://github.com/user-attachments/files/16939868/tenbarma_ko.json)
[tenbarma_mn.json](https://github.com/user-attachments/files/16939881/tenbarma_mn.json)
[tenbarma_mr.json](https://github.com/user-attachments/files/16939866/tenbarma_mr.json)
[tenbarma_ms.json](https://github.com/user-attachments/files/16939874/tenbarma_ms.json)
[tenbarma_ne.json](https://github.com/user-attachments/files/16939880/tenbarma_ne.json)
[tenbarma_pt.json](https://github.com/user-attachments/files/16939873/tenbarma_pt.json)
[tenbarma_ru.json](https://github.com/user-attachments/files/16939879/tenbarma_ru.json)
[tenbarma_sw.json](https://github.com/user-attachments/files/16939882/tenbarma_sw.json)
[tenbarma_th.json](https://github.com/user-attachments/files/16939871/tenbarma_th.json)
[tenbarma_vi.json](https://github.com/user-attachments/files/16939878/tenbarma_vi.json)
[tenbarma_zh.json](https://github.com/user-attachments/files/16939867/tenbarma_zh.json)

**Comment by tenzin3** [comment]
@drupchen 

Few corrections were needed to parse the above translations data.

**1.tenbarma_es.csv**
_Removed the first line_
```
Oración por el Futuro del Dharma,,,,
,BO,EN,ZH,ES
author,སངས་རྒྱས་ཤཀྱ་ཐུབ་པ།,Buddha Shakyamuni,,Buddha Shakyamuni
composition_date,,,,
source,,,,
presentation,,,,
usage_title,,Prayer for the future of the Dharma - Spanish,,Oración por el Futuro del Dharma
title_short,,,,
title_long_clean,,,,
title_alt_1,,,,
title_alt_2,,,,
status,,AI draft,,AI draft
is_commentary_of,,,,
is_version_of,,,,
is_translation_of,བསྟན་འབར་མ།,,,
lang,es,,,

```

**2.tenbarma_ja.csv**
_Removed the first line_
```
,,,,
,BO,EN,ZH,JA
author,སངས་རྒྱས་ཤཀྱ་ཐུབ་པ།,Buddha Shakyamuni,,釈迦牟尼仏 
composition_date,,,,
source,,,,
presentation,,,,
usage_title,,Prayer for the future of the Dharma - Japanese,,「仏法の未来のための祈り」
title_short,,,,
title_long_clean,,,,
title_alt_1,,,,
title_alt_2,,,,
status,,AI draft,,AI draft
is_commentary_of,,,,
is_version_of,,,,
is_translation_of,བསྟན་འབར་མ།,,,
lang,ja,,,

```

**Comment by drupchen** [comment]
@tenzin3, since these are translations, they shouldn't be separate json files, but they should add new sections in the existing .json file for བསྟན་འབར་མ། that has been ingested in pecha db.

**Comment by tenzin3** [comment]
@drupchen , here are the serialized trisarangama json files


[trisaranagama-toh0225-kpzhangjm-021-wm-01.bo.json](https://github.com/user-attachments/files/17008461/trisaranagama-toh0225-kpzhangjm-021-wm-01.bo.json)

[trisaranagama-toh0225-kpzhangjm-021-wm-01.zh.json](https://github.com/user-attachments/files/17008462/trisaranagama-toh0225-kpzhangjm-021-wm-01.zh.json)
